name: release

on:
    push:
        branches: "release/v*"
permissions:
    contents: write
jobs:
    checkout:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_ACCESS_TOKEN}}
                  fetch-depth: 0

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Get the changelog
              run: |
                  export VERSION=$(git tag |grep v | tail -1)
                  export PREVIOUS_VERSION=$(git tag |grep v | tail -2 | head -1)
                  export CHANGES=$(git log --pretty="- %s" $PREVIOUS_VERSION..)
                  printf "# Changelog (\`$VERSION\`)\n\n##Changes\n$CHANGES" > CHANGELOG.md

            - name: Save chagenlog
              run: |
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add .
                  git commit -m 'docs: Обновить CHANGELOG'
                  git push
